version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vox
      POSTGRES_PASSWORD: vox
      POSTGRES_DB: vox40
    volumes:
      - ./data:/var/lib/postgresql/data